### ISSUE TITLE
App GUI freezes

### ISSUE THREAD

**Issue by y0sif** [Mostaqem/mostaqem_desktop#57]
if the downloads page is open, and a surah is deleted from file explorer, the GUI freezes, if there is a surah playing it won't stop.

**Comment by the-sabra** [comment]
Can you tell me what is your OS?

**Comment by y0sif** [comment]
Windows 11

**Comment by MezoPeeta** [comment]
@y0sif can you please check if this problem still persists ?

**Comment by y0sif** [comment]
the problem is no longer there, GUI does not freeze anymore.
