### ISSUE TITLE
Change Request

### ISSUE THREAD

**Issue by devbn3li** [Mostaqem/mostaqem_desktop#66]
السور بتاع المنشاوي بعد مبيقرأ فى اطفال بتقرأ بعده ف ياريت لو تغير ده وتشوف ساوند ليه وحده
ده موقع فيه ساوند ليه وحده لو مش لاقي 
https://mp3quran.net/ar/minsh

**Comment by MezoPeeta** [comment]
هو دا نفس الموقع الي بنستخدمه منه , ممكن تغير التلاواة لحفص عن عاصم من icon التلاوة تحت
